name: Build and deploy Node.js project to Azure Function App - acs-outboundv3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1) Check out
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Set up Node
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3) Install dependencies + build
      - name: 'Install + Build'
        run: |
          npm install
          npm run build --if-present
          # If you want tests:
          # npm run test --if-present

      # 4) Rename dist/OutboundCallFunction => OutboundCallFunction
      - name: Rename compiled folder
        run: |
          rm -rf OutboundCallFunction
          mv dist/OutboundCallFunction OutboundCallFunction

      # 5) Zip for deployment
      - name: Zip artifact
        run: |
          zip -r release.zip \
            OutboundCallFunction \
            node_modules \
            host.json \
            package.json \
            package-lock.json \
            -x '*.git*' \
               'dist/*' \
               'OutboundCallFunction/*.ts'

      # 6) Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1) Download artifact from build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # 2) Unzip
      - name: Unzip artifact
        run: unzip release.zip

      # 3) Azure login (Publish Profile)
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e7da47a509ab4b97ba9755302c68f9da }}

      # 4) Deploy with Azure Functions Action
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'acs-outboundv3'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          # If you prefer, you can remove the 'publish-profile' here since we did azure/login above
          # publish-profile: ${{ secrets.AzureAppService_PublishProfile_e7da47a509ab4b97ba9755302c68f9da }}
