name: Build and deploy Node.js project to Azure Function App - acs-outboundv2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 1) Install dependencies at the root (where package.json is)
      - name: Install dependencies
        run: npm install

      # 2) Build => compiles TS + copies function.json => dist/OutboundCallFunction/
      - name: Build
        run: npm run build

      # 3) Zip only the needed artifacts. 
      #    We EXCLUDE the raw OutboundCallFunction/ folder (with .ts) 
      #    so the function host doesn't pick it up.
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip \
            dist \
            node_modules \
            host.json \
            package.json \
            package-lock.json \
            -x '*.git*' \
               'OutboundCallFunction/*'  # <--- exclude the source folder
          # Explanation:
          #  - 'dist/' has your compiled JS + function.json
          #  - 'node_modules/' has your runtime dependencies
          #  - 'host.json' is needed at the root
          #  - exclude the raw OutboundCallFunction folder to avoid .ts confusion

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'acs-outboundv2'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_252078F4C6044536BB38C08443C7EA43 }}
          package: '.' 
          sku: 'flexconsumption'
